---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
unzip("activity.zip")
activity <- read.csv("activity.csv")

## What is mean total number of steps taken per day?
1.
steps.date <- aggregate(steps ~ date, data=activity, FUN=sum)
barplot(steps.date$steps, names.arg=steps.date$date, xlab="date", ylab="steps")

2.
mean(steps.date$steps)
median(steps.date$steps)

## What is the average daily activity pattern?
1.
steps.interval <- aggregate(steps ~ interval, data=activity, FUN=mean)
plot(steps.interval, type="l")

2.
steps.interval$interval[which.max(steps.interval$steps)]

## Imputing missing values
1.
   sum(is.na(activity))
2.
   
3.
		activity <- merge(activity, steps.interval, by="interval", suffixes=c("",".y"))
		nas <- is.na(activity$steps)
		activity$steps[nas] <- activity$steps.y[nas]
		activity <- activity[,c(1:3)]
4.
		steps.date <- aggregate(steps ~ date, data=activity, FUN=sum)
		barplot(steps.date$steps, names.arg=steps.date$date, xlab="date", ylab="steps")
		mean(steps.date$steps)
		median(steps.date$steps)

## Are there differences in activity patterns between weekdays and weekends?
 1.
		   daytype <- function(date) {
		    if (weekdays(as.Date(date)) %in% c("Saturday", "Sunday")) {
		        "weekend"
		    } else {
		        "weekday"
		    }
		}
		activity$daytype <- as.factor(sapply(activity$date, daytype))
2.
	  par(mfrow=c(2,1))
		for (type in c("weekend", "weekday")) {
		    steps.type <- aggregate(steps ~ interval,
		                            data=activity,
		                            subset=activity$daytype==type,
		                            FUN=mean)
		    plot(steps.type, type="l", main=type)
		}